version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest 
    container_name: ollama_service  # Custom name for the Ollama container
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    runtime: nvidia  # Ensures the NVIDIA runtime is used for this service
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1 # 1 gpu
              capabilities: [gpu]
  app:
    build: .
    image: app_image:latest  # Custom image name
    container_name: app_service  # Custom image name
    ports:
      - "8501:8501"  # Streamlit
      - "8888:8888"  # Jupyter
    environment:
      - OLLAMA_HOST=ollama:11434
      - LLAMA_PARSE_TOKEN=${LLAMA_PARSE_TOKEN}
    depends_on:
      - ollama

volumes:
  ollama_models:

# Construye y levanta los servicios:
# docker compose build && docker compose up